/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dobokocka2;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class NewJFrame extends javax.swing.JFrame {

     private int toke = 1000;
     
     private  final String kep1="/1pont.png";
     private  final String kep2="/2pont.png";
     private  final String kep3="/3pont.png";
     private  final String kep4="/4pont.png";
     private  final String kep5="/5pont.png";
     private  final String kep6="/6pont.png";
     
     public String [] kepek = {kep1, kep2, kep3, kep4, kep5, kep6};
    

     /**
      * Creates new form NewJFrame
      */
     public NewJFrame() {
          initComponents();
          myInit();
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          buttonGroup1 = new javax.swing.ButtonGroup();
          jLabel1 = new javax.swing.JLabel();
          jPanel1 = new javax.swing.JPanel();
          jTextField1 = new javax.swing.JTextField();
          jButton2 = new javax.swing.JButton();
          jLabel2 = new javax.swing.JLabel();
          jPanel2 = new javax.swing.JPanel();
          jSlider1 = new javax.swing.JSlider();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          jLabel6 = new javax.swing.JLabel();
          jLabel7 = new javax.swing.JLabel();
          jRadioButton1 = new javax.swing.JRadioButton();
          jRadioButton2 = new javax.swing.JRadioButton();
          jRadioButton3 = new javax.swing.JRadioButton();
          jRadioButton4 = new javax.swing.JRadioButton();
          jRadioButton5 = new javax.swing.JRadioButton();
          jRadioButton6 = new javax.swing.JRadioButton();
          jLabel8 = new javax.swing.JLabel();
          jLabel9 = new javax.swing.JLabel();
          jButton3 = new javax.swing.JButton();
          jButton1 = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setTitle("Dobókocka dobás");

          jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
          jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel1.setText("Dobókocka dobás");

          jPanel1.setBackground(new java.awt.Color(204, 204, 204));

          jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
          jTextField1.setText("1000");

          jButton2.setText("kezd? t?ke");
          jButton2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
               }
          });

          jLabel2.setForeground(new java.awt.Color(0, 0, 0));
          jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
          jLabel2.setText("1000");

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(174, 174, 174)
                    .addComponent(jButton2)
                    .addGap(97, 97, 97)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(11, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel2))
                    .addContainerGap())
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton2)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          jPanel2.setBackground(new java.awt.Color(204, 204, 204));

          jSlider1.setMaximum(1000);
          jSlider1.setMinimum(1);
          jSlider1.setValue(1);
          jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
               public void stateChanged(javax.swing.event.ChangeEvent evt) {
                    jSlider1StateChanged(evt);
               }
          });

          jLabel3.setForeground(new java.awt.Color(0, 0, 0));
          jLabel3.setText("Add meg a tétet:");

          jLabel4.setForeground(new java.awt.Color(0, 0, 0));
          jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
          jLabel4.setText("1000");

          jLabel5.setForeground(new java.awt.Color(0, 0, 0));
          jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
          jLabel5.setText("1");

          jLabel6.setForeground(new java.awt.Color(0, 0, 0));
          jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
          jLabel6.setText("1000");

          jLabel7.setForeground(new java.awt.Color(0, 0, 0));
          jLabel7.setText("Tipp");

          buttonGroup1.add(jRadioButton1);
          jRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
          jRadioButton1.setText("1");

          buttonGroup1.add(jRadioButton2);
          jRadioButton2.setForeground(new java.awt.Color(0, 0, 0));
          jRadioButton2.setText("2");

          buttonGroup1.add(jRadioButton3);
          jRadioButton3.setForeground(new java.awt.Color(0, 0, 0));
          jRadioButton3.setText("3");

          buttonGroup1.add(jRadioButton4);
          jRadioButton4.setForeground(new java.awt.Color(0, 0, 0));
          jRadioButton4.setText("4");

          buttonGroup1.add(jRadioButton5);
          jRadioButton5.setForeground(new java.awt.Color(0, 0, 0));
          jRadioButton5.setText("5");

          buttonGroup1.add(jRadioButton6);
          jRadioButton6.setForeground(new java.awt.Color(0, 0, 0));
          jRadioButton6.setText("6");

          jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1pont.png"))); // NOI18N

          jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
          jLabel9.setForeground(new java.awt.Color(0, 0, 0));
          jLabel9.setText("Eredmény");

          jButton3.setText("Sorsolás");
          jButton3.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
          jPanel2.setLayout(jPanel2Layout);
          jPanel2Layout.setHorizontalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addGap(43, 43, 43)
                              .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addComponent(jRadioButton6)
                              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                   .addGap(129, 129, 129)
                                   .addComponent(jRadioButton5)))
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addGap(21, 21, 21)
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(jRadioButton2)
                                   .addComponent(jRadioButton1)
                                   .addComponent(jRadioButton3))
                              .addGap(79, 79, 79)
                              .addComponent(jRadioButton4)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jLabel6)
                              .addGap(108, 108, 108))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                              .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                              .addComponent(jButton3)
                              .addGap(76, 76, 76)
                              .addComponent(jLabel8)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(92, 92, 92))
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(98, 98, 98)
                    .addComponent(jLabel7)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
          jPanel2Layout.setVerticalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel5)
                         .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel3)
                         .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addGap(78, 78, 78)
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(jRadioButton4))
                              .addGap(26, 26, 26)
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jRadioButton5)
                                   .addComponent(jRadioButton2)
                                   .addComponent(jButton3))
                              .addGap(25, 25, 25)
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jRadioButton6)
                                   .addComponent(jRadioButton3))
                              .addContainerGap())
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                              .addComponent(jLabel7)
                              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel8)
                                        .addGap(63, 63, 63))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addGap(142, 142, 142))))))
          );

          jButton1.setText("Kilépés");
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addGap(39, 39, 39))
               .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(16, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(34, 34, 34)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButton1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          String ertek = jTextField1.getText();
          try {
               toke = Integer.parseInt(ertek);
          } catch (NumberFormatException e) {
               JOptionPane.showConfirmDialog(null, "Hibás értéket adtál meg", "Figyelem!", JOptionPane.WARNING_MESSAGE);
          }

          if (toke <= 0) {
               toke = 1000;
               JOptionPane.showMessageDialog(null, "A t?két $1000-ra állítottam be", "Figyelem!", JOptionPane.INFORMATION_MESSAGE);
          }

          jTextField1.setVisible(false);
          jButton2.setVisible(false);
          jPanel2.setVisible(true);
          jLabel2.setText("$" + toke);

          jSlider1.setMaximum(toke);

     }//GEN-LAST:event_jButton2ActionPerformed

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          System.exit(0);
     }//GEN-LAST:event_jButton1ActionPerformed

     private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
          jLabel4.setText("" + jSlider1.getValue());
     }//GEN-LAST:event_jSlider1StateChanged

     private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          

          int randomSz = sorsolas();
          System.out.println(randomSz);
          
          if((jRadioButton1.isSelected() && randomSz==1) || (jRadioButton2.isSelected() && randomSz==2 )|| (jRadioButton3.isSelected() && randomSz==3 )  || 
                  (jRadioButton4.isSelected() && randomSz==4) ||  (jRadioButton5.isSelected() && randomSz==5) || (jRadioButton6.isSelected() && randomSz==6)){
              
               toke+= (jSlider1.getValue())*6;
               jLabel9.setText("Nyertél!");
               jLabel9.setForeground(Color.green);
               
               
          } else{
               toke-= jSlider1.getValue();
                jLabel9.setText("Vesztettél!");
                jLabel9.setForeground(Color.red);
          }
          
          
          jLabel4.setText("$"+toke);
          jLabel6.setText(""+toke);
          jSlider1.setMaximum(toke);
          
          if(toke==0){
               JOptionPane.showMessageDialog(null, "Elfogyotta pénzed", "Figyelem!", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
          }
  
          
          
          for (int i = 0; i < kepek.length; i++) {
               if(randomSz==i+1){
                     jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource(kepek[i]))); // NOI18N
                    
               }
               
          }
          
          
     }//GEN-LAST:event_jButton3ActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    new NewJFrame().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.ButtonGroup buttonGroup1;
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JButton jButton3;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JLabel jLabel9;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JRadioButton jRadioButton1;
     private javax.swing.JRadioButton jRadioButton2;
     private javax.swing.JRadioButton jRadioButton3;
     private javax.swing.JRadioButton jRadioButton4;
     private javax.swing.JRadioButton jRadioButton5;
     private javax.swing.JRadioButton jRadioButton6;
     private javax.swing.JSlider jSlider1;
     private javax.swing.JTextField jTextField1;
     // End of variables declaration//GEN-END:variables

     private void myInit() {
          jPanel2.setVisible(false);
     }

     public static int sorsolas() {

          return (int) (Math.random() * 6) + 1;

     }

}
